<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="base" params="plate_radius plate_height length width height mass wheel_radius wheel_pos_z">
    <link name="base_footprint"/>

    <link name="base_link">
      <visual>
        <origin xyz="0 0 -0.01" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://linorobot2_description/urdf/meshes/chassis.stl" scale="1 1 1"/>
        </geometry>
        <material name="grey">
          <color rgba="0.8 0.8 0.8 1.0"/>
        </material>
      </visual>

      <visual>
        <origin xyz="0 0 0.02" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://linorobot2_description/urdf/meshes/chassis_top.stl" scale="1 1 1"/>
        </geometry>
        <material name="grey"/> </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${plate_radius}" length="${plate_height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * mass * ((width * width) + (height * height))}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * ((length * length) + (height * height))}" iyz="0.0"
                 izz="${(1/12) * mass * ((length * length) + (width * width))}"/>
      </inertial>
    </link>

    <link name="ultrasonic_holder_link">
      <visual>
        <origin xyz="0.01 0.02 -0.03" rpy="${pi/2} 0 ${pi/2}"/>
        <geometry>
          <mesh filename="package://linorobot2_description/urdf/meshes/Ultrasonic_Holder.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="blue">
          <color rgba="0.0 0.0 0.8 1.0"/>
        </material>
      </visual>
    </link>

    <joint name="base_to_holder_joint" type="fixed">
      <parent link="base_link"/>
      <child link="ultrasonic_holder_link"/>
      <origin xyz="0.07 0.0 -0.0285" rpy="0 0 0"/>
    </joint>

    <gazebo reference="base_link">
      <visual>
        <material>
          <ambient>0.8392 0.6314 0.0 1.0</ambient>
          <diffuse>0.8392 0.6314 0.0 1.0</diffuse>
          <specular>0.99 0.99 0.99 1.0</specular>
          <emissive>0.0 0.0 0.0 0.0</emissive>
        </material>
      </visual>
    </gazebo>

    <joint name="base_to_footprint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${wheel_radius - wheel_pos_z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
</robot>
